services:

    Dontdrinkandroot\BridgeBundle\Form\Type\FlexDateType:
        tags:
            - { name: form.type, alias: flexdate }

    Dontdrinkandroot\BridgeBundle\Routing\NestedLoader:
        arguments:
            - '@file_locator'
        tags: [ routing.loader ]

    Dontdrinkandroot\BridgeBundle\Service\EncryptionService:
        autoconfigure: true
        autowire: true

    Dontdrinkandroot\BridgeBundle\Command\Encrypt\GenerateKeyCommand:
        autoconfigure: true
        autowire: true

    Dontdrinkandroot\BridgeBundle\Controller\Security\LoginAction:
        autoconfigure: true
        autowire: true
        tags: ['controller.service_arguments']

    Dontdrinkandroot\BridgeBundle\Controller\Security\LogoutAction:
        autoconfigure: true
        autowire: true
        tags: [ 'controller.service_arguments' ]
