version: '3'

services:

    web:
        build:
            dockerfile: docker/prod/Dockerfile
            context: ../../
        image: bandhub.org/website:prod
        ports:
            - "8000:80"
#        depends_on:
#            - postgres

#    postgres:
#        image: postgres:14.5
#        ports:
#            - "5432:5432"
#        environment:
#            POSTGRES_USER: 'user'
#            POSTGRES_PASSWORD: 'password'
#            POSTGRES_DB: 'database'

networks:
    default:
        name: development
        external: true
