services:

    Dontdrinkandroot\BridgeBundle\Service\DdrCrudAdmin\DefaultUuidEntityProvider:
        arguments:
            - '@doctrine'
        tags:
            - name: ddr_crud_admin.item_provider
              priority: -150
            - name: ddr_crud_admin.id_provider
              priority: -150
