services:

    Dontdrinkandroot\BridgeBundle\Form\Type\FlexDateFormType:
        tags:
            - { name: form.type, alias: flexdate }

    Dontdrinkandroot\BridgeBundle\Routing\NestedLoader:
        arguments:
            - '@file_locator'
        tags: [ routing.loader ]

    Dontdrinkandroot\BridgeBundle\Service\EncryptionService:
        autoconfigure: true
        autowire: true

    Dontdrinkandroot\BridgeBundle\Command\Encrypt\GenerateKeyCommand:
        autoconfigure: true
        autowire: true
