version: '3'

services:

    web:
        image: 'dontdrinkandroot/php:8-2-alpine-symfony-dev'
        ports:
            - "8000:80"
#        depends_on:
#            - postgres
        volumes:
            - ../../:/var/www/

#    postgres:
#        image: postgres:14.5
#        ports:
#            - "5432:5432"
#        environment:
#            POSTGRES_USER: 'user'
#            POSTGRES_PASSWORD: 'password'
#            POSTGRES_DB: 'database'

networks:
    default:
        name: development
        external: true
