services:

    app:
        image: dontdrinkandroot/php:symfony-dev-8.5
        extra_hosts:
            - host.docker.internal:host-gateway
        tty: true
        ports:
            - "8000:80"
        volumes:
            - ../../:/app
#        depends_on:
#            - postgres

#    postgres:
#        image: postgres:18.3
#        ports:
#            - "5432:5432"
#        environment:
#            POSTGRES_USER: 'user'
#            POSTGRES_PASSWORD: 'password'
#            POSTGRES_DB: 'database'

networks:
    default:
        name: development
        external: true
